# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datagram.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tagram.proto\"\'\n\x0b\x41\x64\x64ressData\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\xc9\x01\n\x11\x43onfigurationData\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x15\n\rprovider_port\x18\x02 \x01(\x05\x12\x15\n\rconsumer_port\x18\x03 \x01(\x05\x12\x11\n\thost_port\x18\x04 \x01(\x05\x12\x19\n\x11samples_per_block\x18\x05 \x01(\x05\x12\x13\n\x0bsample_rate\x18\x06 \x01(\x01\x12\x1a\n\x12num_input_channels\x18\x07 \x01(\x05\x12\x1b\n\x13num_output_channels\x18\x08 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datagram_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESSDATA._serialized_start=18
  _ADDRESSDATA._serialized_end=57
  _CONFIGURATIONDATA._serialized_start=60
  _CONFIGURATIONDATA._serialized_end=261
# @@protoc_insertion_point(module_scope)
